# Generated by Django 4.0 on 2021-12-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_car_slots', models.IntegerField()),
                ('no_of_bike_slots', models.IntegerField()),
            ],
            options={
                'db_table': 'parking_lot',
            },
        ),
        migrations.CreateModel(
            name='Parkingslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.IntegerField()),
                ('slot_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'parking_slot',
            },
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], max_length=10)),
                ('start_tume', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parkingapp.parkingslot')),
            ],
            options={
                'db_table': 'vehicle_details',
            },
        ),
    ]
