# Generated by Django 4.0 on 2021-12-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledetails',
            old_name='start_tume',
            new_name='start_time',
        ),
    ]
