# Generated by Django 4.0 on 2021-12-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0002_rename_start_tume_vehicledetails_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkingLot',
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together={('slot_no', 'slot_type')},
        ),
    ]
